### PR TITLE
Fixed linting errors from Chrome Dev editor in the tests folder.

### PR DESCRIPTION
**Pull request by CaptainBaxter**

### CODE REVIEW

**Comment by CaptainBaxter** [comment]
I signed it!

**Comment by addyosmani** [comment]
First commit LGTM. Second changes code style, so deferring to @garlicnation for further thoughts.

**Comment by CaptainBaxter** [comment]
Sorry Addy, what's LGTM? Just noticed that the test runners are throwing up failures on GitHub, going to investigate locally and get back to you.

**Comment by addyosmani** [comment]
LGTM = looks good to me. Thanks for exploring the failures.

**Comment by garlicnation** [comment]
Chrome dev editor should exclude this folder from linting. js-parse-error.js is meant to be a parse error. The tests are failing because the test that expects an exception to be thrown on invalid input isn't catching an exception.

I'm OK merging the changes to js-elements if you revert the changes to js-parse-error, however.

**Pull request closed without merging**
