### PR TITLE
node users need lib/ directory

### PR DESCRIPTION
**Pull request by garlicnation**

### CODE REVIEW

**Comment by rictic** [comment]
Which users need lib? npm users? bower users?

**Comment by garlicnation** [comment]
npm users need lib. I would like to make releases tags of master, not leaves that have been built. This CL enables releasing by running `git pull` and `mversion`

**Comment by justinfagnani** [comment]
It doesn't seem like modifying .gitignore is the right way to do this. You can include other files in a release, no? Or release from a branch that includes the files?

**Comment by leodido** [comment]
+1

**Comment by rictic** [comment]
`npm publish` goes off of working directory, not git state, so this change is unnecessary for publishing versions up to npm. We would need to check things in like this if we want to support people doing an npm install directly from git/github.

**Comment by rictic** [comment]
Closing this PR. It seems like this isn't the direction that we're going with our built node modules.

**Pull request closed without merging**
