### PR TITLE
trim whitespace when parsing jsdoc

### LINKED ISSUE #854: JSDoc with windows line endings don't get parsed correctly
With a jsdoc like this:

```ts
/**
 * foo
 * @customElement
 */
```

Assuming windows line endings (CRLF), this results in a `description` of `foo * @customElement` or some such thing.

The reason is that in [removeLeadingAsterisks](https://github.com/Polymer/polymer-analyzer/blob/49592f848c0d5972b5d0836dcdab332a748a82be/src/javascript/jsdoc.ts#L79).

We split on `\n`, it could be changed to `split(/\r?\n/)` or something. Or we find out why the regex in there doesn't match (it doesn't strip the leading asterisks...).

### PR DESCRIPTION
**Pull request by 43081j**
Fixes #854.

There's some funkiness going on with the pattern here so I just trim it to drop any leftover newlines or CRs.

### CODE REVIEW

**Comment by rictic** [comment]
I like it, it needs a test. Simplest way would be to parse from a string with an InMemoryOverlayUrlLoader so that you can write the file under test as a string literal with `\r\n`, to be sure that git doesn't mess with the line endings.

**Comment by 43081j** [comment]
Would it not be simpler (and doesn't it make more sense) to add the test to the existing `parseJsdoc` suite?

we already have `jsdoc_test.ts`.

**Comment by rictic** [comment]
Oh, sure yes!

**Comment by 43081j** [comment]
Here you go :)

**Pull request merged**
