### PR TITLE
Support new properties/observers getters in Polymer 2.0 elements

### PR DESCRIPTION
**Pull request by justinfagnani**
- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by justinfagnani** [comment]
Nope, not missing anything. We just weren't actually handling them before. We were passing the config ObjectLiteral node only to the getProperties() function.

**Comment by usergenic** [comment]
Oh...maybe the reason we don't need them shown here is because we don't have a plan for incorporating Observers in our analysis yet anyways?

**Comment by usergenic** [comment]
k.

**Comment by justinfagnani** [comment]
Linting will probably want that info at some point, but for now it's just internal implementation detail.

**Pull request merged**
