### PR TITLE
 Analyze @global functions, and respect @function name override.

### PR DESCRIPTION
**Pull request by aomarks**
Part of https://github.com/Polymer/gen-typescript-declarations/issues/23

(Also ran clang-format, so look at the second commit separately.)

 - [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by FredKSchott** [comment]
Huh, looks like a new update changed a few style things with clang-format:
http://lists.llvm.org/pipermail/llvm-bugs/2017-February/053609.html

I much prefer the whitespace between `async` & `(`, but since it's not an option with clang-format I guess 🤷‍♂️

**Comment by aomarks** [comment]
Yeah, I just ran `npm run format` in the first commit. Didn't bump the clang version or anything. It seems like we're not regularly running clang format.

**Comment by aomarks** [comment]
Also, the more recent version of clang-format does put the space after async. I'm happy to bump it and run it over everything.

**Comment by FredKSchott** [comment]
Yes please! (when you have time)

**Comment by aomarks** [comment]
https://github.com/Polymer/polymer-analyzer/pull/775

**Pull request merged**
