### PR TITLE
Extract out common code from polymer elements and polymer element mixins into a mixin.

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md not updated, internal change

### CODE REVIEW

**Comment by justinfagnani** [comment]
@rictic is this one of the superceded PRs?

**Comment by rictic** [comment]
No, this implements the Polymer-specific magic as a mixin. Unsure if the deduplication is worth losing type safety on constructor arguments but I'll rebase and send it over to see.

**Comment by justinfagnani** [comment]
We'll have to deal with the constructor arguments issue one way or another as we adopt mixins. I think there's ways to mitigate.

**Comment by rictic** [comment]
Rebased, this is ready to review

**Comment by FredKSchott** [comment]
Closing this PR as abandoned.

@rictic please take a look and rebase/reopen if this is something you'd still like to get merged in.

**Comment by aomarks** [comment]
Closing this pull request because this repo is now archived. If this PR is still active, please submit a new one at https://github.com/Polymer/tools.

**Pull request closed without merging**
