### PR TITLE
Fix slash character compatibility in the default filter

### PR DESCRIPTION
**Pull request by jindav**
On Windows the file parsing, when using the default configuration, filters out scripts because the base path uses forward slash in the script tag and backslash on the filesystem.

### CODE REVIEW

**Comment by jindav** [comment]
I signed it!

**Comment by hypnoce** [comment]
+1

**Comment by garlicnation** [comment]
Please rebase against master and confirm this passes the full test suite.

**Comment by jindav** [comment]
Branch is up-to-date, ci tests are green. Should be safe to merge. Thanks and sorry for the delay.

**Pull request closed without merging**
